import { EventType } from "../../../services/utils/BackendEnums"

const fakerData = [
  {
    id: 1,
    title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    description: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.CONCERT,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 2,
    title: "qui est esse",
    description: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.THEATRE,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 3,
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    description: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.STANDUP,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 4,
    title: "eum et est occaecati",
    description: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.STANDUP,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 5,
    title: "nesciunt quas odio",
    description: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.CONCERT,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 6,
    title: "dolorem eum magni eos aperiam quia",
    description: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.THEATRE,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 7,
    title: "magnam facilis autem",
    description: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.THEATRE,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 8,
    title: "dolorem dolore est ipsam",
    description: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
    startOn: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.CONCERT,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
  {
    id: 9,
    title: "Should not appear on event index page!",
    description: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    startOn: "2025-01-26 16:35:00",
    duration: "02:35:00",
    type: EventType.CONCERT,
    room: { name: 'Salle 1' },
    picture: "/event_picture.jpg",
  },
]

const fakerEvents = {
  datas: fakerData,
  status: 200
}

export { fakerEvents }
