const fakerData = [
  {
    volunteer_id: 1,
    event_id: 1,
    task_id: 1,
    event_title: "La teuf",
    event_start_on: "2021-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: "5",
  },
  {
    volunteer_id: 1,
    event_id: 2,
    task_id: 6,
    event_title: "La teuf 2",
    event_start_on: "2022-01-26 16:35:00",
    task_name: "sound",
    volunteer_assignment_rating: "4",
  },
  {
    volunteer_id: 1,
    event_id: 3,
    task_id: 1,
    event_title: "La teuf 3",
    event_start_on: "2023-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: "4",
  },
  {
    volunteer_id: 1,
    event_id: 4,
    task_id: 1,
    event_title: "La teuf 4",
    event_start_on: "2021-04-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: undefined,
  },
  {
    volunteer_id: 1,
    event_id: 5,
    task_id: 1,
    event_title: "La teuf 5",
    event_start_on: "2021-01-08 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: "2",
  },
  {
    volunteer_id: 2,
    event_id: 6,
    task_id: 1,
    event_title: "Concert 6",
    event_start_on: "2021-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: "4",
  },
  {
    volunteer_id: 2,
    event_id: 2,
    task_id: 1,
    event_title: "La Teuf 2",
    event_start_on: "2023-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: "2",
  },
  {
    volunteer_id: 3,
    event_id: 2,
    task_id: 1,
    event_title: "La Teuf 2",
    event_start_on: "2023-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: undefined,
  },
  {
    volunteer_id: 4,
    event_id: 2,
    task_id: 1,
    event_title: "La Teuf 2",
    event_start_on: "2023-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: undefined,
  },
  {
    volunteer_id: 5,
    event_id: 2,
    task_id: 1,
    event_title: "La Teuf 2",
    event_start_on: "2023-01-26 16:35:00",
    task_name: "ticket_office",
    volunteer_assignment_rating: undefined,
  },
]

const fakerEventsAssigned = {
  datas: fakerData,
  status: 200
}

export { fakerEventsAssigned }