const fakerData = [
  {
    volunteer_id: 1,
    task_id: 1,
    event_id: 1,
    title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    description: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    start_on: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: "concert",
    room: 'Salle 1',
    picture: "/event_picture.jpg",
    task_name: "Task 1",
    comment: undefined,
  },
  {
    volunteer_id: 1,
    task_id: 2,
    event_id: 2,
    title: "qui est esse",
    description: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
    start_on: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: "theatre",
    room: 'Salle 1',
    picture: "/event_picture.jpg",
    task_name: "Task 2",
    comment: 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla',
  },
  {
    volunteer_id: 1,
    task_id: 6,
    event_id: 3,
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    description: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
    start_on: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: "one_man_show",
    room: 'Salle 1',
    picture: "/event_picture.jpg",
    task_name: "Task 6",
    comment: 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut',
  },
  {
    volunteer_id: 1,
    task_id: 5,
    event_id: 5,
    title: "nesciunt quas odio",
    description: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
    start_on: "2021-01-26 16:35:00",
    duration: "02:35:00",
    type: "concert",
    room: 'Salle 1',
    picture: "/event_picture.jpg",
    task_name: "Task 5",
    comment: undefined,
  },
]

const fakerVolunteerAssignmentsComments = {
  datas: fakerData,
  status: 200
}

export { fakerVolunteerAssignmentsComments }